version: '3'

services:
  jmchardy-nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs
      - /home/administrator/nginx.321Tag.conf:/etc/nginx/nginx.conf.template
      - /storage/video_processor_mike/recordings:/opt/recordings:rw
      - /tmp/nginx-rtmp:/tmp/nginx-rtmp:rw
      - /storage/video_processor_mike/uploads:/opt/uploads:rw
